spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: czy1212
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.example.demo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
