package com.example.demo.dao;

import com.example.demo.domain.Page;
import com.example.demo.domain.User;
import java.util.List;

public interface UserMapper {

    //自定义分页
    List<User> selectUserByPage(Page page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_layuiuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_layuiuser
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_layuiuser
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_layuiuser
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_layuiuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}