package com.example.demo.entity;

import java.io.Serializable;

public class Game implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.cn_name
     *
     * @mbg.generated
     */
    private String cn_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.jp_name
     *
     * @mbg.generated
     */
    private String jp_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.en_name
     *
     * @mbg.generated
     */
    private String en_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.nature
     *
     * @mbg.generated
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.generation
     *
     * @mbg.generated
     */
    private String generation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.power
     *
     * @mbg.generated
     */
    private String power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.hirate
     *
     * @mbg.generated
     */
    private String hirate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bootstrap-table..game.pp
     *
     * @mbg.generated
     */
    private String pp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.id
     *
     * @return the value of bootstrap-table..game.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.id
     *
     * @param id the value for bootstrap-table..game.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.cn_name
     *
     * @return the value of bootstrap-table..game.cn_name
     *
     * @mbg.generated
     */
    public String getCn_name() {
        return cn_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.cn_name
     *
     * @param cn_name the value for bootstrap-table..game.cn_name
     *
     * @mbg.generated
     */
    public void setCn_name(String cn_name) {
        this.cn_name = cn_name == null ? null : cn_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.jp_name
     *
     * @return the value of bootstrap-table..game.jp_name
     *
     * @mbg.generated
     */
    public String getJp_name() {
        return jp_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.jp_name
     *
     * @param jp_name the value for bootstrap-table..game.jp_name
     *
     * @mbg.generated
     */
    public void setJp_name(String jp_name) {
        this.jp_name = jp_name == null ? null : jp_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.en_name
     *
     * @return the value of bootstrap-table..game.en_name
     *
     * @mbg.generated
     */
    public String getEn_name() {
        return en_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.en_name
     *
     * @param en_name the value for bootstrap-table..game.en_name
     *
     * @mbg.generated
     */
    public void setEn_name(String en_name) {
        this.en_name = en_name == null ? null : en_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.nature
     *
     * @return the value of bootstrap-table..game.nature
     *
     * @mbg.generated
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.nature
     *
     * @param nature the value for bootstrap-table..game.nature
     *
     * @mbg.generated
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.generation
     *
     * @return the value of bootstrap-table..game.generation
     *
     * @mbg.generated
     */
    public String getGeneration() {
        return generation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.generation
     *
     * @param generation the value for bootstrap-table..game.generation
     *
     * @mbg.generated
     */
    public void setGeneration(String generation) {
        this.generation = generation == null ? null : generation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.power
     *
     * @return the value of bootstrap-table..game.power
     *
     * @mbg.generated
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.power
     *
     * @param power the value for bootstrap-table..game.power
     *
     * @mbg.generated
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.hirate
     *
     * @return the value of bootstrap-table..game.hirate
     *
     * @mbg.generated
     */
    public String getHirate() {
        return hirate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.hirate
     *
     * @param hirate the value for bootstrap-table..game.hirate
     *
     * @mbg.generated
     */
    public void setHirate(String hirate) {
        this.hirate = hirate == null ? null : hirate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.type
     *
     * @return the value of bootstrap-table..game.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.type
     *
     * @param type the value for bootstrap-table..game.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bootstrap-table..game.pp
     *
     * @return the value of bootstrap-table..game.pp
     *
     * @mbg.generated
     */
    public String getPp() {
        return pp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bootstrap-table..game.pp
     *
     * @param pp the value for bootstrap-table..game.pp
     *
     * @mbg.generated
     */
    public void setPp(String pp) {
        this.pp = pp == null ? null : pp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cn_name=").append(cn_name);
        sb.append(", jp_name=").append(jp_name);
        sb.append(", en_name=").append(en_name);
        sb.append(", nature=").append(nature);
        sb.append(", generation=").append(generation);
        sb.append(", power=").append(power);
        sb.append(", hirate=").append(hirate);
        sb.append(", type=").append(type);
        sb.append(", pp=").append(pp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}