

spring:
  datasource:
    username: root
    password: czy1212
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.56.187:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.domain
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 80

#server:
#  port: 9999
#  address: 39.98.56.187