
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: czy1212
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

    devtools:
      restart:
        enabled: true #开启热部署
        additional-paths: src/main/java #热部署目录

server:
  port: 8888




#  原有的key，例如spring.jpa.properties.hibernate.dialect，按“.”分割，都变成树状的配置
#  key后面的冒号，后面一定要跟一个空格
#  把原有的application.properties删掉。然后一定要执行一下  maven -X clean install

#       spring.datasource.url = jdbc:mysql://localhost:3306/newbirds
#       spring.datasource.username = root
#       spring.datasource.password = mymysql
#       spring.datasource.driverClassName = com.mysql.jdbc.Driver
#       # Specify the DBMS
#       spring.jpa.database = MYSQL
#       # Show or not log for each sql query
#       spring.jpa.show-sql = true
#       # Hibernate ddl auto (create, create-drop, update)
#       spring.jpa.hibernate.ddl-auto = update
#       # Naming strategy
#       spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#
#       # stripped before adding them to the entity manager)
#       spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect