
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  #global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #field-strategy: 2
    #驼峰下划线转换
    #db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true

  configuration:
  #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，
  #自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    use-generated-keys: false
    map-underscore-to-camel-case: true

    #cache-enabled: false
    #jdbc-type-for-null: null #配置JdbcTypeForNull, oracle数据库必须配置


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootstrap-table
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: czy1212
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #JDBC配置
      url: jdbc:mysql://localhost:3306/bootstrap-table
      username: root
      password: czy1212
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 5000
      pool-prepared-statements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
      # StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      # 下面的配置表示通过 http://ip:port/druid 来查看数据库信息
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: czy
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


#springboot使用的默认日志框架是Logback 开启日志
#logging:
#  level:
#    root: info
#    org.springframework.web: warn
#    org.apache.tomcat: warn
#    com.example.demo: debug
#  #本地路径
#  file: /Users/cunethan/Desktop/Java/demo-mybatis-plus/logs/test2.log
#logging:
#  config: classpath:logs/logback.xml

