package com.example.demo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.demo.entity.Game;
import java.util.List;

public interface GameMapper extends BaseMapper<Game> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    Game selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    List<Game> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bootstrap-table..game
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Game record);
}